### ISSUE TITLE
Eval images metrics does not show in WanDB

### ISSUE THREAD

**Issue by ichsan2895** [WU-CVGL/BAD-Gaussians#3] opened 2024-03-21 15:24 UTC
Eval images metrics does not show in `WanDB`. It just shows GPU memory, Train loss, Train iter, and ETA
![image](https://github.com/WU-CVGL/BAD-Gaussians/assets/60387342/a2f16c2e-c047-40d6-bf8b-8f46e04ed3e6)

Installation:
```
git clone --branch 8e0c68754b2c440e2d83864fac586cddcac52dc4 https://github.com/nerfstudio-project/nerfstudio
cd nerfstudio
pip install -e .

cd ../

git clone https://github.com/LingzheZhao/gsplat
cd gsplat
git submodule update --init --recursive
pip install -e .

cd ../

git clone https://github.com/WU-CVGL/BAD-Gaussians
cd BAD-Gaussians
pip install -e .
```

Run command:
```
ns-process-data images --data IMAGES --output-dir path/to/scene

ns-train bad-gaussians --logging.steps-per-log 200 --vis viewer+wandb --viewer.websocket-port 7007 \
    --data path/to/scene \
    --pipeline.model.camera-optimizer.mode "cubic" \
    --vis viewer+wandb \
    image-restore-data --downscale_factor 1
```

System information:
```
Ubuntu 22.04 LTS
Python 3.10
Pytorch 2.0.1+cu118
```

**Comment by LingzheZhao** [comment] 2024-03-21 17:45
Sorry for the rambling. TL;DR: The *novel-view* evaluation needs an extra step after training, in the context of pose-optimizing NeRF/3D-GS, and I will release that script in a week (maybe)

--------

Hi, it seems that you are running BAD-Gaussians on your custom dataset with the ImageRestorationDataparser.

FYI, we focus on two types of missions here, one is *deblurring* and the other is *novel-view synthesis*. For *deblurring*, ground-truth sharp images are required in the `images_test` folder for evaluation ([written here](https://github.com/WU-CVGL/BAD-Gaussians/blob/185c82534327d7cc58301103c9b07126f24ae8d1/bad_gaussians/image_restoration_dataparser.py#L142)), and that is only available with the synthetic datasets. While for the real-word datasets, we can only evaluate the novel-view synthesis.

The ImageRestorationDataparser works for the *deblurring* by default, so if `images_test` is not provided, there won't be any eval images, and the trainer will disable evaluation ([written here](https://github.com/WU-CVGL/BAD-Gaussians/blob/185c82534327d7cc58301103c9b07126f24ae8d1/bad_gaussians/image_restoration_trainer.py#L100)). In this case, if you want to split the images into train & eval (*i.e. novel-view synthesis*), you can pass these arguments after the `image-restore-data`, for example:

```bash
ns-train bad-gaussians --logging.steps-per-log 200 --vis viewer+wandb --viewer.websocket-port 7007 \
    --data path/to/scene \
    --pipeline.model.camera-optimizer.mode "cubic" \
    --vis viewer+wandb \
    image-restore-data --downscale_factor 1 \
    --eval-mode='interval' --eval-interval=8 \
```

Now it will uses every nth frame for eval (*i.e. novel-view synthesis*).

However, the evaluation metrics here can only be used as a reference, not the final result - You will see the PSNR first increases, then it will decrease. This is because the camera poses of the eval images are from COLMAP, and it is not accurate. While the camera poses of the training images are being optimized, the eval ones' are not.

(Also note that in our experiments, the *novel-view* images are sharp, unlike the blurry training images. If blurry images are configured to be eval images, it will not match our output in the evaluation (which will be deblurred sharp images, [written here](https://github.com/WU-CVGL/BAD-Gaussians/blob/185c82534327d7cc58301103c9b07126f24ae8d1/bad_gaussians/bad_gaussians.py#L290C13-L290C17)) and the metrics will be even less informative)

IMO, in a scene reconstruction pipeline, NeRF or 3D-GS, when you are optimizing the camera poses, which means the poses are not accurate, you can't use the poses from COLMAP to render the *novel-view* images - Instead, you should freeze the scene parameters and find the accurate pose for the *novel-view* eval image by optimizing it. At least, that's what we do in `BAD-NeRF` and `BAD-Gaussians`. Perhaps this is why many guys find that pose optimization decreases PSNR (https://github.com/nerfstudio-project/nerfstudio/issues/2863) and (https://github.com/nerfstudio-project/nerfstudio/pull/2891).

Unfortunately, I have little time to refactor the *novel-view* script at the moment as I'm working on some other projects. Right now it still looks like crap, maybe I'll refactor and release the script in a week.

**Comment by ichsan2895** [comment] 2024-03-22 16:39
Thank you for your detailed information. I will try this one later:
```
ns-train bad-gaussians --logging.steps-per-log 200 --vis viewer+wandb --viewer.websocket-port 7007 \
    --data path/to/scene \
    --pipeline.model.camera-optimizer.mode "cubic" \
    --vis viewer+wandb \
    nerfstudio-data --downscale_factor 1 \
    --eval-mode='interval' --eval-interval=8 \
```

**Comment by ZcsrenlongZ** [comment] 2024-03-23 15:25
> Thank you for your detailed information. I will try this one later:
> 
> ```
> ns-train bad-gaussians --logging.steps-per-log 200 --vis viewer+wandb --viewer.websocket-port 7007 \
>     --data path/to/scene \
>     --pipeline.model.camera-optimizer.mode "cubic" \
>     --vis viewer+wandb \
>     nerfstudio-data --downscale_factor 1 \
>     --eval-mode='interval' --eval-interval=8 \
> ```

Have you generate a sharp 3DGS? I run the code on the synthetic dataset, but generate a blury 3DGS? 

https://github.com/WU-CVGL/BAD-Gaussians/assets/47207331/2d6f6f3c-bf10-43b4-a132-340ba47e0841

**Comment by LingzheZhao** [comment] 2024-03-23 19:31
@ichsan2895 @ZcsrenlongZ Apologies for I didn't test the functionality of this code in a fresh-new environment before. I switch to a different PC and installed `nerfstudio`, etc., from scratch, and reproduced the problems above:
- The camera poses are not being optimized, because `camera_opt` was not added to the `param_groups`;
- The metrics of the camera optimizer are missing, because they were not added to the model's training metrics.

I believe these problems should be fixed in [this commit](https://github.com/WU-CVGL/BAD-Gaussians/commit/25155be35f3c2dbdb13af1fb439e90d0523c98ba). Sorry again for the inconvenience!

**Comment by ZcsrenlongZ** [comment] 2024-03-24 06:20
> @ichsan2895 @ZcsrenlongZ Apologies for I didn't test the functionality of this code in a fresh-new environment before. I switch to a different PC and installed `nerfstudio`, etc., from scratch, and reproduced the problems above:
> 
>     * The camera poses are not being optimized, because `camera_opt` was not added to the `param_groups`;
> 
>     * The metrics of the camera optimizer are missing, because they were not added to the model's training metrics.
> 
> 
> My local `nerfstudio` was diverged with the upstream so I missed these lines. I believe these problems should be fixed in [this commit](https://github.com/WU-CVGL/BAD-Gaussians/commit/25155be35f3c2dbdb13af1fb439e90d0523c98ba). Sorry again for the inconvenience!
> 
> ![tensorboard](https://private-user-images.githubusercontent.com/43722188/316265367-4ab526ba-1050-425c-96f2-9c4d3c1a87f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNjEzNzUsIm5iZiI6MTcxMTI2MTA3NSwicGF0aCI6Ii80MzcyMjE4OC8zMTYyNjUzNjctNGFiNTI2YmEtMTA1MC00MjVjLTk2ZjItOWM0ZDNjMWE4N2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA2MTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMTFhMTY2OTUzMDVhZDE4YzA5MTlkYzUwZmUzZTliNjYwZDkxMmExOGRlNDk2NTdlYzZiOGU0MzY1ZmU3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O38NhUzURb03w7X7Th4pp1ehagq0l8uhJ7uu4UoFcj4)
> 
> ![viewer](https://private-user-images.githubusercontent.com/43722188/316265451-34289816-6bf5-4d93-852b-384950683805.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNjEzNzUsIm5iZiI6MTcxMTI2MTA3NSwicGF0aCI6Ii80MzcyMjE4OC8zMTYyNjU0NTEtMzQyODk4MTYtNmJmNS00ZDkzLTg1MmItMzg0OTUwNjgzODA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA2MTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MTJkY2QzNzZlMjgzNTAzYjBkZWY1ZDJhZTcyOThjNzE3OWY4ZmFmNmVlZmRlNmI3M2FkODczMGI4NmZhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gEVa5QbZzYUmGkC4aDNCCIMT2lT4RsjWOYrAlJ-EoS4)

Yes!  It works! Thanks for your help!

https://github.com/WU-CVGL/BAD-Gaussians/assets/47207331/a139e920-df21-4521-9a4f-3d7f2a293af5

**Comment by ichsan2895** [comment] 2024-03-24 22:33
Why it does not work with me...
```
# clean up previous version
pip uninstall gsplat bad-gaussians

git clone --branch 8e0c68754b2c440e2d83864fac586cddcac52dc4 https://github.com/nerfstudio-project/nerfstudio
cd nerfstudio
pip install -e .

pip install git+https://github.com/LingzheZhao/gsplat

cd ../

git clone https://github.com/WU-CVGL/BAD-Gaussians
cd BAD-Gaussians
pip install -e .
```

This is the latest bad-gaussians commit = https://github.com/WU-CVGL/BAD-Gaussians/commit/25155be35f3c2dbdb13af1fb439e90d0523c98ba

The code for running `Dblur-nerf` dataset:
```
>> ns-train bad-gaussians \
    --data /workspace/BAD-GAUSSIAN/data/real_camera_motion_blur/blurparterre \
    --pipeline.model.camera-optimizer.mode "cubic" \
    --vis viewer+wandb \
    deblur-nerf-data \
    --downscale_factor 4

Traceback (most recent call last):
  File "/usr/local/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/workspace/NERFSTUDIO_v102/nerfstudio/nerfstudio/scripts/train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/workspace/NERFSTUDIO_v102/nerfstudio/nerfstudio/configs/method_configs.py", line 724, in <module>
    all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_methods())
  File "/workspace/NERFSTUDIO_v102/nerfstudio/nerfstudio/plugins/registry.py", line 43, in discover_methods
    spec = discovered_entry_points[name].load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workspace/BAD-GAUSSIAN/BAD-Gaussians/bad_gaussians/bad_config_method.py", line 12, in <module>
    from bad_gaussians.image_restoration_dataparser import ImageRestorationDataParserConfig
ModuleNotFoundError: No module named 'bad_gaussians.image_restoration_dataparser'
```

**Comment by LingzheZhao** [comment] 2024-03-25 05:01
> Why it does not work with me...
> 
> ```
> # clean up previous version
> pip uninstall gsplat bad-gaussians
> 
> git clone --branch 8e0c68754b2c440e2d83864fac586cddcac52dc4 https://github.com/nerfstudio-project/nerfstudio
> cd nerfstudio
> pip install -e .
> 
> pip install git+https://github.com/LingzheZhao/gsplat
> 
> cd ../
> 
> git clone https://github.com/WU-CVGL/BAD-Gaussians
> cd BAD-Gaussians
> pip install -e .
> ```
> 
> This is the latest bad-gaussians commit = [25155be](https://github.com/WU-CVGL/BAD-Gaussians/commit/25155be35f3c2dbdb13af1fb439e90d0523c98ba)
> 
> The code for running `Dblur-nerf` dataset:
> 
> ```
> >> ns-train bad-gaussians \
>     --data /workspace/BAD-GAUSSIAN/data/real_camera_motion_blur/blurparterre \
>     --pipeline.model.camera-optimizer.mode "cubic" \
>     --vis viewer+wandb \
>     deblur-nerf-data \
>     --downscale_factor 4
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/ns-train", line 5, in <module>
>     from nerfstudio.scripts.train import entrypoint
>   File "/workspace/NERFSTUDIO_v102/nerfstudio/nerfstudio/scripts/train.py", line 62, in <module>
>     from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
>   File "/workspace/NERFSTUDIO_v102/nerfstudio/nerfstudio/configs/method_configs.py", line 724, in <module>
>     all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_methods())
>   File "/workspace/NERFSTUDIO_v102/nerfstudio/nerfstudio/plugins/registry.py", line 43, in discover_methods
>     spec = discovered_entry_points[name].load()
>   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/workspace/BAD-GAUSSIAN/BAD-Gaussians/bad_gaussians/bad_config_method.py", line 12, in <module>
>     from bad_gaussians.image_restoration_dataparser import ImageRestorationDataParserConfig
> ModuleNotFoundError: No module named 'bad_gaussians.image_restoration_dataparser'
> ```
> 
> I also get similar error with `ns-train bad-gaussians -h`. Already report it in this thread = [ ns-train bad-gaussians -h gives error ](https://github.com/WU-CVGL/BAD-Gaussians/issues/5)

Hi, I also left a comment there. Sry this is caused by recent remove of `image_restoration_dataparser`, as it may have caused some confusion in #3. You can first uninstall the `bad_gaussians`:

```
pip uninstall bad_gaussians
```

Then reinstall it, the problem should be gone.

(This only happens if you have installed it before)

**Comment by LingzheZhao** [comment] 2024-03-25 05:33
This is very strange! Can you try also reinstalling nerfstudio with bad_gaussians?

Oh is the underscore '_' in bad_gaussians misspelled by a  hypen '-'?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ichsan2895** [comment] 2024-03-29 16:20
Thanks @LingzheZhao 

I had success with  this fix:
```
pip uninstall gsplat nerfstudio bad-gaussians

pip install git+https://github.com/LingzheZhao/gsplat.git@f62f4132351a65ee4552dd0a42212b86dd90036f

# If it work, dont touch it. I am afraid the newest commit of nerfstudio caused new problem
pip install git+https://github.com/nerfstudio-project/nerfstudio.git@ae6c46cfeaebbe28f9cd48fa986755e27b5f0ae2

# latest commit as 28th March 2024
pip install git+https://github.com/WU-CVGL/BAD-Gaussians.git@5f664ef26e527a9e6bca47ef14bd0ee461bbde7c
```

**Closed** 2024-03-29 23:44 UTC
